apiVersion: v1
kind: ConfigMap 
metadata:
  name: 321done-configmap 
data:
  # Configuration values can be set as key-value properties
  server: 321done
  CONFIG_123DONE: "./config-cluster-untrusted.json"
  REDIS_HOST: redis-service
  PORT: "10139"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 321done
  labels:
    type: 321done
spec:
  selector:
    matchLabels:
      app: 321done
  replicas: 1
  template:
    metadata:
      labels:
        app: 321done
    spec:
      containers:
      - name: 321done
        image: peteroffthestrip/fxa:1.0.4
        ports:
        - containerPort: 10139
        envFrom:
        - configMapRef:
            name: root-configmap
        - configMapRef:
            name: 321done-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: service-321done
spec:
  selector:
    app: 321done
  ports:
  - port: 10139
    targetPort: 10139
