apiVersion: v1
kind: ConfigMap 
metadata:
  name: fortress-configmap 
data:
  # Configuration values can be set as key-value properties
  server: fortress
  CONFIG_FORTRESS: ./config.json
  PORT: "9292"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress
  labels:
    type: fortress
spec:
  selector:
    matchLabels:
      app: fortress
  replicas: 1
  template:
    metadata:
      labels:
        app: fortress
    spec:
      containers:
      - name: fortress
        image: peteroffthestrip/fxa:1.0.4
        ports:
        - containerPort: 9292
        envFrom:
        - configMapRef:
            name: root-configmap
        - configMapRef:
            name: fortress-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-service
spec:
  selector:
    app: fortress
  ports:
  - port: 9292
    targetPort: 9292
    
