apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxa-profile-server-worker
  labels:
    type: fxa-profile-server-worker
spec:
  selector:
    matchLabels:
      app: fxa-profile-server-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: fxa-profile-server-worker
    spec:
      containers:
      - name: fxa-profile-server-worker
        image: peteroffthestrip/fxa:1.0.4
        ports:
        - containerPort: 1113
        envFrom:
        - configMapRef:
            name: root-configmap
        - configMapRef:
            name: fxa-profile-server-configmap
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: port
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: fxa-profile-service-worker
spec:
  selector:
    app: fxa-profile-server-worker
  ports:
  - port: 1113
    targetPort: 1113
    
