apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    type: memcached
spec:
  selector:
    matchLabels:
      app: memcached
#      role: master
#      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
#        role: master
#        tier: backend
    spec:
      containers:
      - name: memcached
        image: memcached
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-service
spec:
  selector:
    app: memcached
  ports:
  - port: 11211
    targetPort: 11211
    
