apiVersion: v1
kind: ConfigMap 
metadata:
  name: mozilla-sync-configmap 
data:
  # Configuration values can be set as key-value properties
  SYNCSERVER_PUBLIC_URL: http://mozilla-sync-service:5000
  SYNCSERVER_BATCH_UPLOAD_ENABLED: "true"
  SYNCSERVER_FORCE_WSGI_ENVIRON: "false"
  SYNCSERVER_DEBUG_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozilla-sync
  labels:
    type: mozilla-sync
spec:
  selector:
    matchLabels:
      app: mozilla-sync
  replicas: 1
  template:
    metadata:
      labels:
        app: mozilla-sync
    spec:
      containers:
      - name: mozilla-sync
        image: mozilla/syncserver:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mozilla-sync-configmap
        env:
        - name: SYNCSERVER_SQLURI
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: uri
        - name: SYNCSERVER_SECRET
          valueFrom:
            secretKeyRef:
              name: keys-secret
              key: syncserver
---
apiVersion: v1
kind: Service
metadata:
  name: mozilla-sync-service
spec:
  selector:
    app: mozilla-sync
  ports:
  - port: 5000
    targetPort: 5000
    
