apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Configuration values can be set as key-value properties
  host: [base64encoded-hostname]
  port: [base64encoded-port]
  user: [base64encoded-user]
  password: [base64encoded-password]
  # Remember to update the base uri whenever you update any of the fields above.  Format starts with pymysql://user:pass@host:port/db
  uri: [base64encoded-pymysql://user:pass@host:port/db]

